# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colsan_small_group', to='otree.Session')),
            ],
            options={
                'db_table': 'colsan_small_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('random_id', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('punishment_endowment', otree.db.models.IntegerField(null=True)),
                ('punishment_sent', otree.db.models.IntegerField(default=0, null=True)),
                ('punishment_received', otree.db.models.IntegerField(default=0, null=True)),
                ('punishment_received_in', otree.db.models.IntegerField(default=0, null=True)),
                ('punishment_received_out', otree.db.models.IntegerField(default=0, null=True)),
                ('pair', otree.db.models.IntegerField(null=True)),
                ('pd_received_mult', otree.db.models.IntegerField(null=True)),
                ('endowment_remain', otree.db.models.IntegerField(null=True)),
                ('punishment_endowment_remain', otree.db.models.IntegerField(null=True)),
                ('pun_r_in_mult', otree.db.models.IntegerField(null=True)),
                ('pun_r_out_mult', otree.db.models.IntegerField(null=True)),
                ('subgroup', otree.db.models.StringField(max_length=10000, null=True)),
                ('pd_decision', otree.db.models.IntegerField(null=True, verbose_name='Your sending decision')),
                ('pd_payoff', otree.db.models.IntegerField(default=0, null=True)),
                ('payoff_stage2', otree.db.models.IntegerField(default=0, null=True)),
                ('ingroup_punishment', otree.db.models.IntegerField(null=True, verbose_name='Sending deduction tokens to your group member')),
                ('outgroup_punishment', otree.db.models.IntegerField(null=True, verbose_name='Sending deduction tokens to another group member')),
                ('outgroup_punishee_decision', otree.db.models.IntegerField(null=True)),
                ('ingroup_punishee_decision', otree.db.models.IntegerField(null=True)),
                ('participant_vars_dump', otree.db.models.StringField(max_length=10000, null=True)),
                ('tot_minutes_waited', otree.db.models.IntegerField(null=True)),
                ('payoff_minutes_waited', otree.db.models.FloatField(null=True)),
                ('payoff_min_added', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colsan_small.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colsan_small_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colsan_small_player', to='otree.Session')),
            ],
            options={
                'db_table': 'colsan_small_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colsan_small_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'colsan_small_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('cur_page', otree.db.models.IntegerField(null=True)),
                ('opened', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('diff', models.DurationField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='otree.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colsan_small.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colsan_small.Subsession'),
        ),
    ]
